name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "17"]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
